name       : ruby-rb-inotify
version    : 0.9.10
release    : 1
source     :
    - https://rubygems.org/downloads/rb-inotify-0.9.10.gem : e140f7ad14cd91e001c7e0bfa32458dd29995e70932765fcf477de630b7fda79
license    : MIT
component  : programming.ruby
summary    : RubyGem - rb-inotify
description: |
    A Ruby wrapper for Linux inotify, using FFI.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby-ffi
install    : |
    %gem_install
